"""Opt-in titles copied from agent-authored note text; never generated by the host."""
import re

POLICY = 'agent-first-line-v1'
INSTRUCTION = ('Begin each notebook entry with a short descriptive heading on its first nonblank line. '
               'That line becomes the document title shown in search (up to 120 characters); '
               'the complete entry remains unchanged.')


def entry_title(text):
    line=next(line.strip() for line in text.splitlines() if line.strip())
    heading=re.sub(r'^#{1,6}\s+', '', line).strip()
    return (heading or line)[:120]
